# Generated by Django 5.0.6 on 2025-03-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PAS', models.CharField(max_length=30)),
            ],
        ),
    ]
