# Generated by Django 5.1.7 on 2025-06-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='ROLE',
            field=models.CharField(default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='EMAIL',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='NAME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='PAS',
            field=models.CharField(max_length=128),
        ),
    ]
